### PR TITLE
Fixes

### LINKED ISSUE #1: Usage of 'period' and 'windowSize' is inconsistent

### PR DESCRIPTION
**Pull request by tlsim**
#1 #3 #4

@chrisprice 
@ColinEberhardt

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Great job, lots of useful fixes there. The only part I'm not keen on is the documentation change where default values are being described as functions, e.g. `() => 13` - I'm just wondering why that is? From a user perspective they will most likely perceive these properties as taking constant integer values, even though internally they are functor properties.

I also wonder whether these should be functor properties at all? I guess there is an argument that there is no harm in making every property a functor, but in this case I cannot see any real-world application.

see: https://github.com/ScottLogic/d3fc/issues/365

**Comment by chrisprice** [comment]
Agree with the docs change being a bit odd. Given how much witchcraft is associated with indicators I don't see the harm in permitting a variable period.

**Comment by tlsim** [comment]
@ColinEberhardt @chrisprice - docs updated.

**Comment by ColinEberhardt** [comment]
Nice job - and thanks for the detailed semantic commit messages @tlsim

**Pull request merged**
